on:
  issues:
    types: [opened]
  push:
    paths:
      - .github/workflows/add-issue-into-projects.yml
jobs:
  add:
    runs-on: ubuntu-latest
    env:
      ORG: kasaikou
      PROJECT_NUMBER: 8
    steps:
      - name: project/get-project-data
        env:
          GH_TOKEN: ${{ secrets.USER_PAT_GITHUB_PROJECT }}
        run: |
          gh project field-list ${{ env.PROJECT_NUMBER }} --format json
