on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/add-issue-into-projects.yml
      - .github/workflows/update-end-date-on-close.yml
      - .github/workflows/copy-issue-to-awesomedocuments.yml
      - .github/ISSUE_TEMPLATE/**
env:
  ARTIFACT_KEY: copy-issue
  DEPLOY_REPOSITORY: kasaikou/awesomedocuments
  DEPLOY_SECRETS: ${{ secrets.REPO_PAT_KASAIKOU_AWESOMEDOCUMENTS }}
  DEPLOY_USER: Github Actions
  DEPLOY_EMAIL: actions@github.com
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOY_REPOSITORY }}
          token: ${{ env.DEPLOY_SECRETS }}
          path: dest
      - name: copy/copy
        env:
          ARTIFACT_DIR: dest/artifacts/github.com/${{ github.repository }}/workflows/${{ env.ARTIFACT_KEY }}
          GITHUB_TOKEN: ${{ env.DEPLOY_SECRETS }}
        run: |
          rm -rf ${{ env.ARTIFACT_DIR }}
          mkdir -p ${{ env.ARTIFACT_DIR }}/.github/workflows
          cp -f .github/workflows/add-issue-into-projects.yml ${{ env.ARTIFACT_DIR }}/.github/workflows/
          cp -f .github/workflows/update-end-date-on-close.yml ${{ env.ARTIFACT_DIR }}/.github/workflows/
          cp -r .github/ISSUE_TEMPLATE ${{ env.ARTIFACT_DIR }}/.github
          ls -al ${{ env.ARTIFACT_DIR }}/.github
          ls -al ${{ env.ARTIFACT_DIR }}/.github/workflows
          cd ./dest
          git add -A
          git config user.name "${{ env.DEPLOY_USER }}"
          git config user.email "${{ env.DEPLOY_EMAIL }}"
          git commit -m "Actions: Update in ${{ github.repository }}" -m "Updated commit url: https://github.com/${{ github.repository }}/tree/${{ github.sha }}"
          git push
          cd ..          
