on:
  issues:
    types: [closed]
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      ORG: kasaikou
      PROJECT_NUMBER: 8
    steps:
      - name: project/get-issue-data
        env:
          GH_TOKEN: ${{ secrets.USER_PAT_GITHUB_PROJECT }}
        run: |
          gh project list --format json --owner @me > project_config.json
          echo 'PROJECT_ID'=$(jq '.projects[] | select(.number==${{ env.PROJECT_NUMBER }}) | .id' project_config.json) >> $GITHUB_ENV
          gh project item-list ${{ env.PROJECT_NUMBER }} --format json --owner @me > project_item.json
          echo 'PROJECT_ITEM_ID'=$(jq '.items[] | select(.content.url=="${{ github.event.issue.html_url }}") | .id' project_item.json) >> $GITHUB_ENV
          gh project field-list ${{ env.PROJECT_NUMBER }} --format json --owner @me > project_config.json
          cat project_config.json
          echo 'END_DATE_ID='$(jq '.fields[] | select(.name=="End date") | .id' project_config.json) >> $GITHUB_ENV
      - name: project/get-date
        run:
          echo "END_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: project/update-item
        if: ${{ env.PROJECT_ITEM_ID }} == ""
        env:
          GH_TOKEN: ${{ secrets.USER_PAT_GITHUB_PROJECT }}
        run:
          gh project item-edit --format json --project-id ${{ env.PROJECT_ID }} --id ${{ env.PROJECT_ITEM_ID }} --field-id ${{ env.END_DATE_ID }} --date ${{ env.END_DATE }}

